FUNCTIONAL_GROUPS = {
    "Alkene": "[CX3]=[CX3]",
    "Alkyne": "[CX2]#C",
    "Alcohol (Hydroxyl)": "[OX2H]",
    "Ether": "[OD2]([#6])[#6]",
    "Aldehyde": "[CX3H1](=O)[#6]",
    "Ketone": "[CX3](=O)[#6]",
    "Carboxylic Acid": "[CX3](=O)[OX2H1]",
    "Ester": "[CX3](=O)[OX2][#6]",
    "Amide": "[NX3][CX3](=[OX1])[#6]",
    "Amine (Primary)": "[NX3;H2]",
    "Amine (Secondary)": "[NX3;H1]([#6])[#6]",
    "Amine (Tertiary)": "[NX3]([#6])([#6])[#6]",
    "Nitrile": "[CX2]#N",
    "Nitro Group": "[NX3](=O)[O-]",
    "Thiols (Sulfhydryl)": "[SX2H]",
    "Thioether": "[SX2]([#6])[#6]",
    "Halides (Alkyl Halides)": "[F,Cl,Br,I]",
    "Sulfoxide": "[#16X3+1]-[#8X1-]",
    "Sulfone": "[SX4](=O)(=O)[#6]",
    "Epoxide": "C1OC1",
    "Anhydride": "[CX3](=O)O[CX3](=O)",
    "Imine": "[CX3]=[NX3]"
}
