from typing import Dict, List, Tuple, Union, Set
import os
import subprocess
import numpy as np
from utils.chemistry_utils import canonicalize_smiles


# Technically a chemistry utility, but this is likely only used in the constrained-docking oracle
def sdf2smiles(sdf_file: str) -> str:
    """
    Convert an SDF file to its canonical SMILES string.
    """
    output_dir = os.path.dirname(sdf_file)
    output = subprocess.run([
        "obabel",
        "-isdf", sdf_file,
        "-O", os.path.join(output_dir, "temp.smi")
    ], capture_output=True)
    
    try:
        with open(os.path.join(output_dir, "temp.smi"), "r") as f:
            smiles = f.read().strip()
    except FileNotFoundError:
        raise ValueError(f"SDF file {sdf_file} not found")

    return canonicalize_smiles(smiles)


def get_interaction_criteria(interaction_type: str) -> Dict[str, Union[int, float]]:
    # From: https://github.com/rasbt/Hbind
    if interaction_type == "hbond":
        return {
            "distance_lower_bound": 2.4,
            "distance_upper_bound": 3.5,
            "angle_lower_bound": 120,
            "angle_upper_bound": 180
        }
    # TODO: Add criteria for other interaction types (salt-bridge, etc.)
    else:
        raise ValueError(f"Invalid interaction type: {interaction_type}")


def extract_hbind_interactions(
    raw_output: str, 
    interaction_type: str
) -> List[Tuple[Union[str, float]]]:
    """
    Extracts interactions from summary table generated by `Hbind`.
    Example interaction output:
    (
        "hbond",      # Interaction type
        "N.3",        # Ligand atom
        "ASP109",     # Protein residue
        2.729,        # Distance (Å)
        149.2,        # Angle (degrees)
        "Donor - Acceptor"  # Interaction description
    )
    """
    interactions = []
    for line in raw_output.split("\n"):
        if line.startswith(f"| {interaction_type}"):
            parts = line.split()
            ligand_atom = parts[4]
            protein_residue = parts[6]
            residue_number = int(parts[8])
            distance = float(parts[10])
            angle = float(parts[11])
            interaction = " ".join(parts[12:])
            
            interactions.append((
                interaction_type,
                ligand_atom,
                protein_residue + str(residue_number),
                distance,
                angle,
                interaction
            ))
    return interactions


def match_interactions(
    interactions: List[Tuple[Union[str, float]]], 
    enforced_residues: List[str], interaction_type: str
) -> Set[str]:
    """
    Matches interactions to enforced residues based on distance and angle criteria.
    """
    interaction_criteria = get_interaction_criteria(interaction_type)
    enforced_residues_found = set()
    for enforced_residue in enforced_residues:
        for interaction in interactions:
            if enforced_residue in interaction[2]:
                # Check distance and angle criteria
                if (
                    interaction[3] >= interaction_criteria["distance_lower_bound"] and 
                    interaction[3] <= interaction_criteria["distance_upper_bound"] and
                    interaction[4] >= interaction_criteria["angle_lower_bound"] and
                    interaction[4] <= interaction_criteria["angle_upper_bound"]
                ):
                    enforced_residues_found.add(enforced_residue)
    return enforced_residues_found


def dense_reward_multiplier(
    interactions: List[Tuple[Union[str, float]]], 
    enforced_residues: List[str],
    interaction_type: str
) -> float:
    """
    Calculates the dense reward multiplier based on the deviation from the acceptance criteria
    """
    # Contribution of each residue to the total reward
    # TODO: Could allow weighting by residue importance - at the moment, all residues are weighted equally
    alpha = 1.0 / len(enforced_residues)
    alpha_factors = np.zeros(len(enforced_residues))

    interaction_criteria = get_interaction_criteria(interaction_type)

    for idx, enforced_residue in enumerate(enforced_residues):
        distance_factor = 0.0
        angle_factor = 0.0
        for interaction in interactions:
            if enforced_residue in interaction[2]:
                # Check distance criterion
                if interaction[3] >= interaction_criteria["distance_lower_bound"] and interaction[3] <= interaction_criteria["distance_upper_bound"]:
                    # Perfect reward
                    distance_factor = 0.5
                elif interaction[3] < interaction_criteria["distance_lower_bound"]:
                    # Decrease reward by 0.1 for every 0.1 Angstrom deviation
                    deviation = interaction_criteria["distance_lower_bound"] - interaction[3]
                    distance_factor = max(0, 0.5 - (deviation / 0.1 * 0.1))
                elif interaction[3] > interaction_criteria["distance_upper_bound"]:
                    # Decrease reward by 0.1 for every 0.1 Angstrom deviation
                    deviation = interaction[3] - interaction_criteria["distance_upper_bound"]
                    distance_factor = max(0, 0.5 - (deviation / 0.1 * 0.1))

                # Check angle criterion
                if float(distance_factor) == 0.0:
                    angle_factor = 0.0
                elif interaction[4] >= interaction_criteria["angle_lower_bound"] and interaction[4] <= interaction_criteria["angle_upper_bound"]:
                    # Perfect reward
                    angle_factor = 0.5
                elif interaction[4] < interaction_criteria["angle_lower_bound"]:
                    # Decrease reward by 0.1 for every 5 degrees deviation
                    deviation = interaction_criteria["angle_lower_bound"] - interaction[4]
                    angle_factor = max(0, 0.5 - (deviation / 5 * 0.1))
                elif interaction[4] > interaction_criteria["angle_upper_bound"]:
                    # Decrease reward by 0.1 for every 5 degrees deviation
                    deviation = interaction[4] - interaction_criteria["angle_upper_bound"]
                    angle_factor = max(0, 0.5 - (deviation / 5 * 0.1))

                # Break after finding the interaction for the residue
                break

        assert (distance_factor + angle_factor) <= 1.0, "Distance and angle factors should not exceed 1.0"
        alpha_factors[idx] = distance_factor + angle_factor

    # Reward multiplier
    reward_multiplier = sum([alpha * alpha_factor for alpha_factor in alpha_factors])
    assert reward_multiplier <= 1.0, "Reward multiplier should not exceed 1.0"
    return reward_multiplier
